print("Hello World!")
print("What is your name? ")
myName = input()
print("It's good to meet you, " + myName)
print("The lenght of my name is: ")
print(len(myName))
print("What is your age? ")
myAge = input()
print('You will be ' + str(int(myAge) + 1) + ' in a year.') 
print(f'{myName.title()} you will be ' + str(int(myAge) + 1) + ' in a year.') 